# Generated by Django 4.0 on 2023-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='品牌名称')),
                ('img_url', models.CharField(max_length=255, verbose_name='品牌图片')),
                ('img_url_s3', models.ImageField(max_length=255, upload_to='', verbose_name='品牌图片local')),
                ('market_share', models.CharField(max_length=255, verbose_name='市场占有率')),
                ('feedback', models.CharField(max_length=255, verbose_name='好评率')),
                ('price_min', models.CharField(max_length=255, verbose_name='最低价')),
                ('price_max', models.CharField(max_length=255, verbose_name='最高价')),
                ('phone_num', models.CharField(max_length=255, verbose_name='机型数量')),
            ],
            options={
                'verbose_name': '手机品牌',
                'verbose_name_plural': '手机品牌',
                'db_table': 'phone_brand',
            },
        ),
        migrations.CreateModel(
            name='Phone_sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '手机基本信息',
                'verbose_name_plural': '手机基本信息',
                'db_table': 'phone_sku',
            },
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('run_times', models.IntegerField(default=0)),
                ('last_run_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '爬虫',
                'verbose_name_plural': '爬虫',
                'db_table': 'spider',
            },
        ),
    ]
