# Generated by Django 4.0 on 2023-05-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone_brand',
            name='img_url_s3',
            field=models.ImageField(max_length=255, null=True, upload_to='', verbose_name='品牌图片local'),
        ),
        migrations.AlterField(
            model_name='phone_brand',
            name='market_share',
            field=models.FloatField(max_length=255, null=True, verbose_name='市场占有率'),
        ),
    ]
