# Generated by Django 4.1 on 2023-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phone_sku",
            name="img_url_s3",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="手机图片s3存储url"
            ),
        ),
    ]
