# Generated by Django 4.1 on 2023-05-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_phone_sku_img_url_s3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone_sku",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="此条信息创建时间"
            ),
        ),
    ]
