# Generated by Django 4.0 on 2023-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_phone_brand_img_url_s3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone_brand',
            name='id',
        ),
        migrations.RemoveField(
            model_name='phone_sku',
            name='id',
        ),
        migrations.AlterField(
            model_name='phone_brand',
            name='img_url_s3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='品牌图片local'),
        ),
        migrations.AlterField(
            model_name='phone_brand',
            name='market_share',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='市场占有率'),
        ),
        migrations.AlterField(
            model_name='phone_brand',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='品牌名称'),
        ),
        migrations.AlterField(
            model_name='phone_sku',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
