# Generated by Django 4.1 on 2023-05-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_phone_sku_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone_spu",
            fields=[
                (
                    "_id",
                    models.CharField(
                        max_length=124,
                        primary_key=True,
                        serialize=False,
                        verbose_name="手机id",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="手机名称/型号")),
                ("url", models.CharField(max_length=255, verbose_name="页面url")),
                (
                    "img_url",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="手机图片"
                    ),
                ),
                (
                    "img_url_s3",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="手机图片s3存储url"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="此条信息创建时间"
                    ),
                ),
                (
                    "mall_price",
                    models.IntegerField(blank=True, null=True, verbose_name="商城价格"),
                ),
                (
                    "basic_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="基本信息, json格式"
                    ),
                ),
                (
                    "outline",
                    models.TextField(blank=True, null=True, verbose_name="外形, json格式"),
                ),
                (
                    "hardware",
                    models.TextField(blank=True, null=True, verbose_name="硬件, json格式"),
                ),
                (
                    "screen",
                    models.TextField(blank=True, null=True, verbose_name="屏幕, json格式"),
                ),
                (
                    "camera",
                    models.TextField(blank=True, null=True, verbose_name="摄像头, json格式"),
                ),
                (
                    "network",
                    models.TextField(blank=True, null=True, verbose_name="网络, json格式"),
                ),
                (
                    "battery",
                    models.TextField(blank=True, null=True, verbose_name="电池, json格式"),
                ),
                (
                    "phone_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crawler.phone_sku",
                        verbose_name="手机id",
                    ),
                ),
            ],
            options={
                "verbose_name": "手机详细参数",
                "verbose_name_plural": "手机详细参数",
                "db_table": "phone_detail",
            },
        ),
    ]
