# Generated by Django 4.1 on 2023-05-26 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0005_phone_spu_camera_back_phone_spu_camera_front_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phone_spu",
            name="camera_back",
        ),
        migrations.RemoveField(
            model_name="phone_spu",
            name="camera_front",
        ),
        migrations.RemoveField(
            model_name="phone_spu",
            name="cpu",
        ),
        migrations.RemoveField(
            model_name="phone_spu",
            name="display_resolution",
        ),
        migrations.RemoveField(
            model_name="phone_spu",
            name="ram",
        ),
        migrations.RemoveField(
            model_name="phone_spu",
            name="screen_size",
        ),
    ]
