# Generated by Django 4.1 on 2023-05-26 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0007_remove_phone_spu_phone_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phone_sku",
            old_name="created_at",
            new_name="last_modify",
        ),
        migrations.RenameField(
            model_name="phone_spu",
            old_name="created_at",
            new_name="last_modify",
        ),
    ]
