# Generated by Django 4.1 on 2023-05-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0008_rename_created_at_phone_sku_last_modify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone_sku",
            name="last_modify",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="此条信息最后更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="phone_spu",
            name="last_modify",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="此条信息最后更新时间"
            ),
        ),
    ]
