# Generated by Django 4.1 on 2023-05-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0009_alter_phone_sku_last_modify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone_brand",
            name="feedback",
            field=models.FloatField(max_length=255, verbose_name="好评率"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="phone_num",
            field=models.IntegerField(max_length=255, verbose_name="机型数量"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="price_max",
            field=models.IntegerField(max_length=255, verbose_name="最高价"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="price_min",
            field=models.IntegerField(max_length=255, verbose_name="最低价"),
        ),
    ]
