# Generated by Django 4.1 on 2023-05-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0010_alter_phone_brand_feedback_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone_brand",
            name="feedback",
            field=models.FloatField(verbose_name="好评率"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="market_share",
            field=models.FloatField(blank=True, null=True, verbose_name="市场占有率"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="phone_num",
            field=models.IntegerField(verbose_name="机型数量"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="price_max",
            field=models.IntegerField(verbose_name="最高价"),
        ),
        migrations.AlterField(
            model_name="phone_brand",
            name="price_min",
            field=models.IntegerField(verbose_name="最低价"),
        ),
    ]
