# Generated by Django 4.1 on 2023-05-30 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0011_alter_phone_brand_feedback_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Spider",
        ),
    ]
