# Generated by Django 4.1 on 2023-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0012_delete_spider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone_spu",
            name="img_url",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="", verbose_name="手机图片"
            ),
        ),
        migrations.AlterField(
            model_name="phone_spu",
            name="img_url_s3",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="",
                verbose_name="手机图片s3存储url",
            ),
        ),
    ]
